# Generated by Django 4.2.2 on 2023-07-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('fdate', models.DateField()),
                ('ffare', models.FloatField()),
                ('ffrom', models.CharField(max_length=20)),
                ('fto', models.CharField(max_length=20)),
            ],
        ),
    ]
